name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  target:
    description: 'Target to make'
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
